---
- name: "[{{ openio_service_name }}] Create gridinit configuration file"
  template:
    src: "gridinit.conf.j2"
    dest: "{{ openio_service_gridinit_dir }}/{{ openio_service_gridinit_file_prefix }}{{ openio_service_name }}.conf"
    owner: openio
    group: openio
    mode: '0644'
  register: _register_gridinit_conf
  tags: configure

- name: "[{{ openio_service_name }}] Reload gridinit if conf file has changed"
  command: /usr/bin/gridinit_cmd reload
  when:
    - _register_gridinit_conf is changed
    - not openio_service_provision_only
  tags: configure

- name: "[{{ openio_service_name }}] (re)start service if something has changed"
  command: "/usr/bin/gridinit_cmd restart {{ openio_service_gridinit_service_name }}"
  when:
    - _register_gridinit_conf is changed or _register_directories is changed or _register_configuration_files is changed
    - not openio_service_provision_only
  tags: configure
...
